### ISSUE TITLE
FV number included in FV title

### ISSUE THREAD

**Issue by emmalambert19** [innio-mech-dev-sim/Reliability-Management-System#12]
**Is your feature request related to a problem? Please describe.**
FV are more often referred to by number rather than by title.  At the moment, the number is not included with the title for identifying the FVs making this difficult

**Describe the solution you'd like**
Please add the FV number to the title.  Format should be 'FV### - #####' or '### - #####'.  As this information is also included in MyPlant, it should be possible.

**Describe alternatives you've considered**
We have tried with just the title, however, all members of the FV team have requested that the number be added as the title is not sufficient.

**Additional context**
![image](https://github.com/innio-mech-dev-sim/Reliability-Management-System/assets/106756730/7c7bd2ef-86a5-481a-927a-88c2bd09e66b)

**Comment by giovannibrighenti** [comment]
good point!

**Comment by mate-szoke-innio** [comment]
@emmalambert19 The required changes were completed and will be included in the next RMS release. We have also introduced this naming convention to FM and preseries. If you don't see the FV/FM/preseries ID in front of the title, that means the ID is missing. If you encounter a title where an ID is missing and it should not be the case, please let us know.
