### ISSUE TITLE
Not possible to add a plot to 'Engine Data' Tab

### ISSUE THREAD

**Issue by emmalambert19** [innio-mech-dev-sim/Reliability-Management-System#15]
**Describe the bug**
It does not appear to be possible to save / create a new plot in the engine data tab for a validation.

**To Reproduce**
1. RMS Tool - Field Validation (any platform / any project) - Engine data
2. Click on the edit symbol by the FV name
3. Click on 'Add Plot Item'
4. Input plot requirements 
5. Click 'Save configuration'
6. Click the 'x' at the top right of the screen.
7. No additional plot is visible (understand that this may not be possible until the next day when the data is pulled from MyPlant, however...)
8. Refresh the page and return to the edit page as per Step 2.
9. Plot is no longer visible / saved

**Expected behavior**
Additional plot should be visible, at least by the next day, or saved data for the plot should still be visible.

**Screenshots**
![image](https://github.com/innio-mech-dev-sim/Reliability-Management-System/assets/106756730/c38a43ec-50d0-4ddd-8333-1418bb5a86e2)

**Desktop (please complete the following information):**
 - Windows
 - Edge
 - Version 121.0.2277.83 (Official build) (64-bit)

**Comment by mate-szoke-innio** [comment]
@emmalambert19  This bug has been fixed and included within the latest RMS release (v7.0.3).
